AWSTemplateFormatVersion: '2010-09-09'
Resources:
  
  # Elastic Beanstalk Application
  ElasticBeanstalkApplication:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      ApplicationName: "student"
  
  # Elastic Beanstalk Environment
  ElasticBeanstalkEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApplication
      EnvironmentName: "Student-env"
      SolutionStackName: "Python 3.12 running on 64bit Amazon Linux 2023 v4.5.0"

      OptionSettings:
        - Namespace: "aws:autoscaling:asg"
          OptionName: "MinSize"
          Value: "1"
        - Namespace: "aws:autoscaling:asg"
          OptionName: "MaxSize"
          Value: "4"
