AWSTemplateFormatVersion: '2010-09-09'
Resources:
  
  # Elastic Beanstalk Environment (Use existing application)
  ElasticBeanstalkEnvironment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      ApplicationName: "student"  # Use existing application name
      EnvironmentName: "Student-env"
      SolutionStackName: "Python 3.12 running on 64bit Amazon Linux 2023 v4.5.0"

      OptionSettings:
        - Namespace: "aws:autoscaling:asg"
          OptionName: "MinSize"
          Value: "1"
        - Namespace: "aws:autoscaling:asg"
          OptionName: "MaxSize"
          Value: "4"
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: "IamInstanceProfile"
          Value: "aws-elasticbeanstalk-ec2-role"  # Ensure this role exists
